### ISSUE TITLE
[DataModel] Create datamodel for Courses entity

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/talent-manager-schools#2]
The Courses datamodel will contain the following fields:

Table courses {
  id int
  name varchar
  slug varchar
  supplier_id int [ref: - suppliers.id]
  category_id int [ref: - categories.id]
  length float //move to supplier_course_link?
  address varchar //move to supplier_course_link?
  start_date date //move to supplier_course_link?
  end_date date //move to supplier_course_link?
  accredited boolean //move to supplier_course_link?
  price float //move to supplier_course_link?
  credits int //move to supplier_course_link?
  description text //move to supplier_course_link?
  skills varchar //move to supplier_course_link?
  status boolean 
  created_at timestamp
  updated_at timestamp
}

Table categories {
  id int
  name varchar
  description text
}

Table suppliers {
  id int
  name varchar
  email varchar
  phone varchar
  description text
  status boolean
  created_at timestamp
  updated_at timestamp
}

**Comment by cosminbosutar** [comment]
Done
