### ISSUE TITLE
[DataModel] Create data model for Appraisal entity

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/talent-manager-schools#3]
Table appraisals {
  id int
  school_teacher_id int [ref: - school_teacher_link.id]
  semester int
  year int
  revaluation_date date
  status boolean
  created_at timestamp
  updated_at timestamp
}

Table skills {
  id int
  name varchar
  grade_id int [ref: - grades.id]
}

Table appraisal_skill_link {
  skill_id int [ref: - skills.id]
  appraisal_id int [ref: - appraisals.id]
  mark int
}

**Comment by cosminbosutar** [comment]
Done
