### ISSUE TITLE
[DataModel] Create data model for Schools entity

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/talent-manager-schools#4]
Table schools {
  id int
  name varchar
  address varchar
  phone varchar
  email varchar
  school_principal varchar
  inspectorate_id int [ref: - inspectorates.id]
  profile_picture varchar
  description text
  contact_name varchar
  contact_email varchar
  contact_phone varchar
  contact_role varchar
  status boolean
  created_at timestamp
  updated_at timestamp
}

table inspectorates {
  id int
  name varchar
  description text
}

Table school_teacher_link {
  id int
  teacher_id int [ref: - teachers.id]
  school_id int [ref: - schools.id]
}

**Comment by cosminbosutar** [comment]
Done
