### ISSUE TITLE
[DataModel] Create data model for Teacher entity

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/talent-manager-schools#5]
Table teachers {
  id int
  first_name varchar
  last_name varchar
  address varchar
  phone varchar
  birth_date date
  profile_picture varchar
  objectives text
  status boolean
  created_at timestamp
  updated_at timestamp
}

Table specializations {
  id int
  name varchar
  description text
}

Table specialization_teacher_link {
  specialization_id int [ref: - specializations.id]
  teacher_id int [ref: - teachers.id]
}

Table grades {
  id int
  name varchar
  description text
}

Table grade_teacher_link {
  grade_id int [ref: - grades.id]
  teacher_id int [ref: - teachers.id]
}

**Comment by cosminbosutar** [comment]
Done
