### ISSUE TITLE
[DataModel] Create data model for learning plan entity

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/talent-manager-schools#6]
Table learning_plans {
  id int
  teacher_id int [ref: - teachers.id]
  school_id int [ref: - schools.id]
  year int
  status boolean
  created_at timestamp
  updated_at timestamp
}

Table learning_plan_course_link {
  learning_plan_id int [ref: - learning_plans.id]
  course_id int [ref: - courses.id]
  school_covered_costs float
  status int // proposed, rejected
}

**Comment by cosminbosutar** [comment]
Done
